'use client'

import './globals.css'
import { CartProvider } from '../context/CartContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
      <html lang="en">
        <body>
          <CartProvider>
            {children}
          </CartProvider>
        </body>
      </html>
  )
}
